[package]
name = "aho-corasick"
version = "0.7.4"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "Fast multiple substring searching."
homepage = "https://github.com/BurntSushi/aho-corasick"
repository = "https://github.com/BurntSushi/aho-corasick"
readme = "README.md"
keywords = ["string", "search", "text", "aho", "multi"]
license = "Unlicense/MIT"
categories = ["text-processing"]
autotests = false
exclude = ["/aho-corasick-debug", "/bench", "/ci/*", "/.travis.yml", "/sgx/*"]

[badges]
travis-ci = { repository = "BurntSushi/aho-corasick" }
appveyor = { repository = "BurntSushi/regex-automata" }

#[workspace]
#members = ["bench", "aho-corasick-debug"]

[lib]
name = "aho_corasick"

[features]
default = ["std", "mesalock_sgx"]
std = ["memchr/use_std"]
mesalock_sgx = ["sgx_tstd", "memchr/mesalock_sgx"]

[dependencies]
memchr = { git = "https://github.com/mesalock-linux/rust-memchr-sgx", version = "2.2.0", default-features = false }
sgx_tstd = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk.git", optional = true }

[dev-dependencies]
doc-comment = "0.3.1"

[profile.release]
debug = true

[profile.bench]
debug = true
